##########################################################################
#              JoinAndLeave by Neiyko - Configuration file               #
#                 Check frequently for plugin updates!                   #
##########################################################################

#####################
#    Join System    #
#####################
join:
  enable: true

#####################
#   Leave  System   #
#####################
leave:
  enable: true

#####################
# Permission System #
#####################
reload-permission: "joinandleave.reload"