name: JoinAndLeave
version: 1.0.0
main: fr.neiyko.joinandleave.Main
author: Neiyko
description: Plugin allowing to have a message when a player joins or leaves the server
softdepend:
  - LuckPerms
commands:
  jalreload:
    description: Used to reload the plugin