name: JoinAndLeave
version: 1.2
main: fr.neiyko.joinandleave.JoinAndLeave
author: Neiyko
description: Plugin allowing to have a message when a player joins or leaves the server
depend:
  - Vault
commands:
  joinandleave:
    description: Used to reload the plugin
    aliases:
      - jal